subdir-ccflags-y += -I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/include/compat/posix \
                    -I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/include \
					-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src/arch/include \
					-I$(srctree)/ekernel/subsys/net/rt-thread/lwip/src \
					-I$(srctree)/ekernel/drivers/hal/include/hal/aw-alsa-lib \

#subdir-ccflags-y += -DONLY_ENABLE_AUDIO

#subdir-ccflags-y += -DONLY_DISABLE_AUDIO

subdir-ccflags-y += -O0

obj-y += libcedarc/
obj-y += libcedarx/
obj-y += tplayer/
