############################################################################
# apps/examples/t070s140b_touch_test/Makefile
#
# T070S140B LCD IIC Touchscreen Test Application Makefile
#
############################################################################

include $(APPDIR)/Make.defs

# T070S140B Touch Test Application

PROGNAME = $(CONFIG_EXAMPLES_T070S140B_TOUCH_TEST_PROGNAME)
PRIORITY = $(CONFIG_EXAMPLES_T070S140B_TOUCH_TEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_T070S140B_TOUCH_TEST_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_T070S140B_TOUCH_TEST)

MAINSRC = t070s140b_touch_test_main.c

include $(APPDIR)/Application.mk