/* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.

 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the the People's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.

 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.


 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __ARCH_ARM_SRC_R528_DEV_WDT_H
#define __ARCH_ARM_SRC_R528_DEV_WDT_H

#include "sunxi_hal_wdt.h"

#define DEV_NAME    "r528-wdt"

#define R528_WDT_IRQ_EN 0x0
#define R528_WDT_STATUS 0x04
#define R528_WDT_SOFT_RESET 0x08
#define R528_WDT_CTRL 0x10
#define R528_WDT_CFG  0x14
#define R528_WDT_MODE  0x18
#define R528_WDT_OUT_CFG  0x1C
#define R528_WDT_TIMEOUT_SHIFT  4
#define R528_WDT_RESET_MASK  0x03
#define R528_WDT_RESET_MODE  0x01
#define R528_WDT_INTERRUPT_MODE 0x02

#define R528_WDT_BASE 0x020500a0

static struct sunxi_wdt_reg_t r528_wdt_reg =
{
	.wdt_irq_en = R528_WDT_IRQ_EN,
	.wdt_status = R528_WDT_STATUS,
	.wdt_soft_reset = R528_WDT_SOFT_RESET,
	.wdt_ctrl = R528_WDT_CTRL,
	.wdt_cfg = R528_WDT_CFG,
	.wdt_mode = R528_WDT_MODE,
	.wdt_out_cfg = R528_WDT_OUT_CFG,
	.wdt_timeout_shift = R528_WDT_TIMEOUT_SHIFT,
	.wdt_reset_mask = R528_WDT_RESET_MASK,
	.wdt_reset_mode = R528_WDT_RESET_MODE,
	.wdt_interrupt_mode = R528_WDT_INTERRUPT_MODE,
};

static struct sunxi_wdt_info_t r528_wdt_info = {
	.dev_name = DEV_NAME,
};

static struct sunxi_wdt_dev_t r528_wdt_dev = {
	.wdt_base = (void *)R528_WDT_BASE,
	.wdt_regs = &r528_wdt_reg,
	.timeout = 0,
	.wdt_info = &r528_wdt_info,
};

struct sunxi_wdt_dev_t* watchdog_get_dev(void)
{
	return &r528_wdt_dev;
};

#endif /* __ARCH_ARM_SRC_R528_HAL_WDT_H */
