/*
* Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
*
* Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
* the the People's Republic of China and other countries.
* All Allwinner Technology Co.,Ltd. trademarks are used with permission.
*
* DISCLAIMER
* THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
* IF YOU NEED TO INTEGRATE THIRD PARTY¡¯S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
* IN ALLWINNERS¡¯SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
* ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
* ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
* COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
* YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY¡¯S TECHNOLOGY.
*
*
* THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
* PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
* THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
* OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
* NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
* STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __TMR_SUN20IW1_H__
#define __TMR_SUN20IW1_H__

#include <hal_clk.h>

#define SUNXI_TMR_PBASE 0x02050000
#define SUNXI_R_TMR_PBASE 0x07020000
#define SUNXI_HSTIMER_PBASE 0x03008000
#define HTIMER_CTL_REG_OFFSET(id) (0x03008000 + 0x20 + id * 0x20)
#define HTIMER_CNTVAL_LO_REG_OFFSET(id) (0x03008000 + 0x2c + id * 0x20)
#define HTIMER_INTVAL_LO_REG_OFFSET(id) (0x03008000 + 0x24 + id * 0x20)
#define PENDING_BIT(id) (1 << (id))

#define SUNXI_IRQ_HSTIMER0 87
#define SUNXI_IRQ_HSTIMER1 88

#if defined(CONFIG_ARCH_SUN8IW20) /* ARM */
#define SUNXI_GIC_START 32
#elif defined(CONFIG_SOC_SUN20IW1) /* RISC-V */
#define SUNXI_GIC_START 16
#endif

#define SUNXI_IRQ_TMR(id) (SUNXI_GIC_START + 59 + (id))
#define SUNXI_IRQ_R_TMR(id) (SUNXI_GIC_START + 140 + (id))

#define SUNXI_AVS_CLK_TYPE HAL_SUNXI_CCU
#define SUNXI_AVS_CLK   CLK_AVS
#define HTIMER_MAX_NUM  1

#endif /*__TWI_SUN8IW19_H__  */
